FROM docker.io/ollama/ollama:0.1.8

RUN apt-get update && apt-get install -y \
	curl golang-go pandoc

COPY backend/entrypoint.sh backend/models.txt /
RUN chmod +x /entrypoint.sh

COPY gollama /gollama
RUN cd /gollama && go build

EXPOSE 8080
ENTRYPOINT ["/entrypoint.sh"]
