apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: backend
  name: backend
spec:
  containers:
  - image: nsrichan/ai4humanities-translation-engine-backend
    name: backend

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: middleware
  name: middleware
spec:
  containers:
  - image: nsrichan/ai4humanities-translation-engine-gollama
    name: middleware

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    k8s-app: backend-service
spec:
  type: ClusterIP
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    k8s-app: backend

---
