apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-server
  labels:
    k8s-app: translation-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ollama-server
  template:
    metadata:
      labels:
        k8s-app: ollama-server
    spec:
      containers:
      - image: ollama/ollama:0.4.2
        name: ollama-pod
        resources:
          requests:
            cpu: 8
            memory: 32Gi
            # nvidia.com/a100: 1
          limits:
            cpu: 8
            memory: 32Gi
            # nvidia.com/a100: 1
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-models
        env:
        - name: PATH
          value: "/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
      volumes:
      - name: ollama-models
        persistentVolumeClaim:
          claimName: ollama-models
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi

---

apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    k8s-app: ollama
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 11434
  selector:
    k8s-app: ollama-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-server
  labels:
    k8s-app: translation-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: entity-server
  template:
    metadata:
      labels:
        k8s-app: entity-server
    spec:
      containers:
      - image: nsrichan/ai4humanities-translation-engine:entities
        imagePullPolicy: Always
        name: entity-pod
        resources:
          requests:
            cpu: 8
            memory: 8Gi
          limits:
            cpu: 8
            memory: 8Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /models
          name: entity-models
        env:
        - name: PATH
          value: "/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: MODELS_PATH
          value: "/models"
      volumes:
      - name: entity-models
        persistentVolumeClaim:
          claimName: entity-models
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: entity-models
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi

---

apiVersion: v1
kind: Service
metadata:
  name: entity
  labels:
    k8s-app: entity
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    k8s-app: entity-server

---
