apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: backend
  name: backend
spec:
  containers:
  - image: nsrichan/ai4humanities-translation-engine:dev
    name: backend
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: 8
        memory: 16Gi
        nvidia.com/gpu: 1
  # tolerations:
  # - key: "nautilus.io/nrp-testing"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: nvidia.com/gpu.product
           operator: In
           values:
           - NVIDIA-A100-SXM4-80GB
         - key: kubernetes.io/hostname
           operator: In
           values:
           - node-1-1.sdsc.optiputer.net

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    k8s-app: backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: backend

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: backend-ingress
spec:
  rules:
  - host: dcct.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 8080
  tls:
  - hosts:
    - dcct.nrp-nautilus.io
